version: "3"
services:
  react-app:
    build:
      context: .
      dockerfile: "Dockerfile.dev"
    ports:
      - "5000:3000"
    volumes:
      - /opt/app/node_modules
      - .:/opt/app
    stdin_open: true
  tests:
    build:
      context: .
      dockerfile: "Dockerfile.dev"
    volumes:
      - /opt/app/node_modules
      - .:/opt/app
    command: ["npm", "run", "test"]